// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type ZCRXRedirectZcrxRedirectKey struct {
	_              structs.HostLayout
	IngressIfindex uint32
	DestinationMac [6]uint8
	Pad            uint16
}

type ZCRXRedirectZcrxRedirectValue struct {
	_             structs.HostLayout
	NetkitIfindex uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	ZCRXRedirectMapCiliumZcrx    = "cilium_zcrx"
	ZCRXRedirectProgCilZcrxRedir = "cil_zcrx_redir"
)

// LoadZCRXRedirect returns the embedded CollectionSpec for ZCRXRedirect.
func LoadZCRXRedirect() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ZCRXRedirectBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ZCRXRedirect: %w", err)
	}

	return spec, err
}

// LoadZCRXRedirectObjects loads ZCRXRedirect and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ZCRXRedirectObjects
//	*ZCRXRedirectPrograms
//	*ZCRXRedirectMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadZCRXRedirectObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadZCRXRedirect()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ZCRXRedirectSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ZCRXRedirectSpecs struct {
	ZCRXRedirectProgramSpecs
	ZCRXRedirectMapSpecs
	ZCRXRedirectVariableSpecs
}

// ZCRXRedirectProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ZCRXRedirectProgramSpecs struct {
	CilZcrxRedir *ebpf.ProgramSpec `ebpf:"cil_zcrx_redir"`
}

// ZCRXRedirectMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ZCRXRedirectMapSpecs struct {
	CiliumZcrx *ebpf.MapSpec `ebpf:"cilium_zcrx"`
}

// ZCRXRedirectVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ZCRXRedirectVariableSpecs struct {
}

// ZCRXRedirectObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadZCRXRedirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type ZCRXRedirectObjects struct {
	ZCRXRedirectPrograms
	ZCRXRedirectMaps
	ZCRXRedirectVariables
}

func (o *ZCRXRedirectObjects) Close() error {
	return _ZCRXRedirectClose(
		&o.ZCRXRedirectPrograms,
		&o.ZCRXRedirectMaps,
	)
}

// ZCRXRedirectMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadZCRXRedirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type ZCRXRedirectMaps struct {
	CiliumZcrx *ebpf.Map `ebpf:"cilium_zcrx"`
}

func (m *ZCRXRedirectMaps) Close() error {
	return _ZCRXRedirectClose(
		m.CiliumZcrx,
	)
}

// ZCRXRedirectVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadZCRXRedirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type ZCRXRedirectVariables struct {
}

// ZCRXRedirectPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadZCRXRedirectObjects or ebpf.CollectionSpec.LoadAndAssign.
type ZCRXRedirectPrograms struct {
	CilZcrxRedir *ebpf.Program `ebpf:"cil_zcrx_redir"`
}

func (p *ZCRXRedirectPrograms) Close() error {
	return _ZCRXRedirectClose(
		p.CilZcrxRedir,
	)
}

func _ZCRXRedirectClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed zcrxredirect_bpfeb.o
var _ZCRXRedirectBytes []byte
